name: Build Docker Image

on:
    push:
        branches: [ "main" ]
        paths-ignore: [ "README.md", "LICENSE", "CONTRIBUTING.md", ".github/**" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: triumph-tf2/website

jobs:
    build-and-push-image:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
    deploy:
      runs-on: ubuntu-latest
      needs: build-and-push-image
      steps:
        - name: Deploy to server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script_stop: true
            script: |
              cd /prod/services/web/triumph/website
              docker compose pull
              docker compose up -d
